# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__: str = "unknown"
__repo_version__: str = "unknown"
__fingerprint__: str = "cf1a97ffa09aee5990726953d6a6c1b390af4971 *"
__dependency_versions__: dict[str, str | None] = {}
__all__ = (
    "__version__",
    "__repo_version__",
    "__fingerprint__",
    "__dependency_versions__",
)
