# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__: str = "unknown"
__repo_version__: str = "unknown"
__fingerprint__: str = "421d6d7cb2906ed2726baf0be9287480bb806a72 *"
__dependency_versions__: dict[str, str | None] = {}
__all__ = (
    "__version__",
    "__repo_version__",
    "__fingerprint__",
    "__dependency_versions__",
)
